"""
CORTEX Cloud Autopilot — Core Pydantic Models & Schemas
Defines all structured types for the 10-stage closed control loop:
Observe -> Understand -> Predict -> Simulate -> Optimize -> Authorize -> Act -> Verify -> Learn
"""

from datetime import datetime, timezone
from uuid import uuid4
from typing import Dict, Any, List, Optional, Literal
from pydantic import BaseModel, Field


class TelemetrySnapshot(BaseModel):
    """Raw or aggregated telemetry snapshot for a service at a specific timestamp."""
    service: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    rps: float = 0.0
    error_rate: float = 0.0
    p50_latency_ms: float = 0.0
    p95_latency_ms: float = 0.0
    p99_latency_ms: float = 0.0
    cpu_percent: float = 0.0
    memory_percent: float = 0.0
    active_replicas: int = 1
    queue_depth: int = 0
    source: str = "prometheus"
    is_fresh: bool = True
    age_seconds: float = 0.0


class Incident(BaseModel):
    """A detected or reported operational anomaly."""
    id: str
    title: str
    description: str
    service: str
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = "HIGH"
    detected_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    telemetry: Optional[TelemetrySnapshot] = None
    state: str = "OPEN"


class Diagnosis(BaseModel):
    """Structured AI or analytical root cause diagnosis."""
    incident_id: str
    root_cause: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence_ids: List[str] = Field(default_factory=list)
    alternative_causes: List[str] = Field(default_factory=list)
    hypothesized_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    critique_rebuttal: Optional[str] = None
    revised_confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class ActionProposal(BaseModel):
    """
    Immutable action candidate generated by the AI / IncidentAgent.
    CRITICAL INVARIANT: The AI agent may ONLY produce ActionProposals.
    It has ZERO authority to execute infrastructure mutations directly.
    """
    proposal_id: str = Field(default_factory=lambda: f"prop_{uuid4().hex}")
    incident_id: str
    action_type: str
    target: str
    params: Dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    evidence_ids: List[str] = Field(default_factory=list)
    rationale: str = Field(default="Candidate remediation action")
    reason: Optional[str] = None
    risk_score: int = Field(default=50, ge=0, le=100)
    dry_run: bool = False
    generated_by: str = "cortex-agent"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    state_version: str = "1.0"
    telemetry_timestamp: Optional[str] = None

    def model_post_init(self, __context: Any) -> None:
        if self.reason and (self.rationale == "Candidate remediation action" or not self.rationale):
            self.rationale = self.reason


class SimulationResult(BaseModel):
    """Result of Counterfactual Digital Twin shadow-state evaluation."""
    proposal_id: str
    target_service: str
    current_state: Dict[str, Any]
    shadow_state: Dict[str, Any]
    latency_delta_ms: float
    error_rate_delta_pct: float
    blast_radius: int
    affected_services: List[str]
    is_safe: bool
    confidence: float = 0.85
    assumptions: List[str] = Field(default_factory=list)
    model_version: str = "twin-v2.1"


class GuardDecision(BaseModel):
    """Deterministic authorization decision issued by CORTEX Guard."""
    proposal_id: str
    decision: Literal["ALLOW", "CONSTRAIN", "REQUIRE_APPROVAL", "BLOCK"]
    risk_score: int = Field(ge=0, le=100)
    blast_radius: int = 0
    policy_triggered: Optional[str] = None
    reason: str
    constrained_params: Optional[Dict[str, Any]] = None
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    ttl_seconds: int = 30
    actor_identity: str = "cortex-agent"


class ApprovalRecord(BaseModel):
    """Human-in-the-loop authorization token."""
    approval_id: str
    proposal_id: str
    incident_id: str
    action_type: str
    target: str
    params: Dict[str, Any]
    risk_score: int
    reason: str
    status: Literal["PENDING", "APPROVED", "REJECTED", "EXPIRED", "CONSUMED"] = "PENDING"
    state_version: str = "1.0"
    resource_version: str = ""
    approver: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime
    resolved_at: Optional[datetime] = None


class ExecutionResult(BaseModel):
    """Outcome of real infrastructure mutation executed by Provider."""
    operation_id: str
    proposal_id: str
    action_type: str
    target: str
    params: Dict[str, Any]
    status: Literal["SUCCESS", "FAILED", "BLOCKED", "ROLLED_BACK"]
    output: Dict[str, Any] = Field(default_factory=dict)
    executed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    execution_time_ms: float = 0.0
    idempotency_key: str
    provider_type: str = "sandbox"


class VerificationResult(BaseModel):
    """Post-action closed-loop verification comparing pre vs post measurements."""
    operation_id: str
    service: str
    outcome: Literal["RECOVERED", "PARTIALLY_RECOVERED", "NO_CHANGE", "WORSE", "UNKNOWN"]
    pre_metrics: Dict[str, Optional[float]]
    post_metrics: Dict[str, Optional[float]]
    p95_change_ms: Optional[float]
    error_change_pct: Optional[float]
    slo_satisfied: bool
    verified_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    settling_time_sec: float = 5.0
    rollback_triggered: bool = False
    rollback_result: Optional[Dict[str, Any]] = None
    simulated: bool = False
    telemetry_source: Optional[str] = None
